package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author Aditya Naufal
 */

public class login_form extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
//getterttp sessionttp = new getterttp();
private String nama,id, jabatan;
public static String uName, uId, uJabatan, uTelp, uMail, uPass;
public static String user;
public int b_manajemen,b_manajemen_perusahaan, b_manajemen_perusahaan_tambah, b_manajemen_perusahaan_edit;
    /**
     * Creates new form login
     */
    public login_form() {
        initComponents();
            kosong();
    }
    
    public void kosong()
    {
        txt_uname.setText("U S E R  N A M E");
        txt_pass.setText("11111111");
    }
    
    public void login_id(){
        nama=txt_uname.getText();
            try {       
                String a=String.valueOf(txt_pass.getText());         
                 ResultSet as = conn.createStatement().executeQuery("select id_user,password_user from user where (id_user="
                + "'"+nama+"' and password_user=AES_ENCRYPT('"+a+"','setufitness'))");
                if (as.next()){
                    JOptionPane.showMessageDialog(rootPane, "Berhasil Log-In, Selamat Datang : "+nama+". "); 
                    home hom = new home();
                    user=txt_uname.getText();
                    hom.getId(user);
                    hom.setVisible(true);
                    uName=nama; 

                   
                    dispose();
                }
                else{
                JOptionPane.showMessageDialog(rootPane, "ID atau Password yang anda masukkan salah.");   
                
                }
                }      
            catch (SQLException ex) {
            Logger.getLogger(login_form.class.getName()).log(Level.SEVERE, null, ex);
             }    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_Login1 = new javax.swing.JLabel();
        btn_Login3 = new javax.swing.JLabel();
        btn_Login6 = new javax.swing.JLabel();
        btn_Login7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btn_Login8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        password = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        btn_Login2 = new javax.swing.JLabel();
        btn_Login4 = new javax.swing.JLabel();
        btn_Login5 = new javax.swing.JLabel();
        btn_Login9 = new javax.swing.JLabel();
        txt_uname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABSENSI - LOGIN");
        setAutoRequestFocus(false);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(684, 300));

        jPanel2.setBackground(new java.awt.Color(255, 253, 227));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Login1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_Login1.setForeground(new java.awt.Color(32, 74, 86));
        btn_Login1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Login1.setText("SETU FITNESS CORNER");
        jPanel2.add(btn_Login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 334, 302, -1));

        btn_Login3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Login3.setForeground(new java.awt.Color(32, 74, 86));
        btn_Login3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Login3.setText("GYM'S MANAGEMENT APPS");
        btn_Login3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(btn_Login3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 372, 290, -1));

        btn_Login6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Login6.setForeground(new java.awt.Color(32, 74, 86));
        btn_Login6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Login6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_bench_press_150px.png"))); // NOI18N
        btn_Login6.setText("a");
        btn_Login6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(btn_Login6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 172, -1, -1));

        btn_Login7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_Login7.setForeground(new java.awt.Color(32, 74, 86));
        btn_Login7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Login7.setText("JL. Setu Cipayung, No. 54, , RT.2/RW.4");
        btn_Login7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(btn_Login7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 408, 290, -1));

        jSeparator3.setBackground(new java.awt.Color(32, 74, 86));
        jSeparator3.setForeground(new java.awt.Color(32, 74, 86));
        jSeparator3.setOpaque(true);
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 394, 275, -1));

        btn_Login8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_Login8.setForeground(new java.awt.Color(32, 74, 86));
        btn_Login8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Login8.setText("Cilangkap, Kec. Cipayung, Kota Jakarta Timur");
        btn_Login8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(btn_Login8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 424, 290, -1));

        jPanel3.setBackground(new java.awt.Color(230, 72, 72));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setEditable(false);
        password.setBackground(new java.awt.Color(230, 72, 72));
        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 253, 227));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("P A S S W O R D");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 510, -1));

        txt_pass.setBackground(new java.awt.Color(230, 72, 72));
        txt_pass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(255, 253, 227));
        txt_pass.setText("jPasswordField1");
        txt_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 253, 227)));
        txt_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passFocusGained(evt);
            }
        });
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });
        jPanel3.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 380, 40));

        btn_Login2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_Login2.setForeground(new java.awt.Color(255, 253, 227));
        btn_Login2.setText("X");
        btn_Login2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Login2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Login2MouseClicked(evt);
            }
        });
        jPanel3.add(btn_Login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 17, 36, 35));

        btn_Login4.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        btn_Login4.setForeground(new java.awt.Color(255, 253, 227));
        btn_Login4.setText("   Pengelolahan Sistem Management Gym/Fitness Center, Dirancang Oleh: Adi, Untuk Setu Fitness Corner");
        jPanel3.add(btn_Login4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 427, -1));

        btn_Login5.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        btn_Login5.setForeground(new java.awt.Color(255, 253, 227));
        btn_Login5.setText("Copyrights - 2022");
        jPanel3.add(btn_Login5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, -1, -1));

        btn_Login9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_Login9.setForeground(new java.awt.Color(231, 238, 126));
        btn_Login9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Login9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_user_male_circle_100px.png"))); // NOI18N
        btn_Login9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Login9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Login9MouseClicked(evt);
            }
        });
        jPanel3.add(btn_Login9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 510, -1));

        txt_uname.setBackground(new java.awt.Color(230, 72, 72));
        txt_uname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_uname.setForeground(new java.awt.Color(255, 253, 227));
        txt_uname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 253, 227)));
        txt_uname.setOpaque(true);
        txt_uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_unameFocusGained(evt);
            }
        });
        jPanel3.add(txt_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 370, 40));

        username.setEditable(false);
        username.setBackground(new java.awt.Color(230, 72, 72));
        username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 253, 227));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("U S E R  N A M E");
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 510, -1));

        kButton2.setForeground(new java.awt.Color(32, 74, 86));
        kButton2.setText("C A N C E L");
        kButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(255, 253, 227));
        kButton2.setkBorderRadius(30);
        kButton2.setkEndColor(new java.awt.Color(230, 72, 72));
        kButton2.setkForeGround(new java.awt.Color(32, 74, 86));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 253, 227));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 253, 227));
        kButton2.setkHoverStartColor(new java.awt.Color(230, 72, 72));
        kButton2.setkIndicatorThickness(10);
        kButton2.setkPressedColor(new java.awt.Color(230, 72, 72));
        kButton2.setkStartColor(new java.awt.Color(255, 253, 227));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        kButton3.setForeground(new java.awt.Color(32, 74, 86));
        kButton3.setText("S I G N  I N");
        kButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(255, 253, 227));
        kButton3.setkBorderRadius(30);
        kButton3.setkEndColor(new java.awt.Color(230, 72, 72));
        kButton3.setkForeGround(new java.awt.Color(32, 74, 86));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 253, 227));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 253, 227));
        kButton3.setkHoverStartColor(new java.awt.Color(230, 72, 72));
        kButton3.setkIndicatorThickness(10);
        kButton3.setkPressedColor(new java.awt.Color(230, 72, 72));
        kButton3.setkStartColor(new java.awt.Color(255, 253, 227));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Login9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Login9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Login9MouseClicked

    private void btn_Login2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Login2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_Login2MouseClicked

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           login_id();
         
        }
    }//GEN-LAST:event_txt_passKeyPressed

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passFocusGained
        // TODO add your handling code here:
        txt_pass.setText("");
    }//GEN-LAST:event_txt_passFocusGained

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
     
    }//GEN-LAST:event_passwordFocusGained

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFocusGained

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
        login_id();
        
    }//GEN-LAST:event_kButton3ActionPerformed

    private void txt_unameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_unameFocusGained
        // TODO add your handling code here:
        txt_uname.setText("");
    }//GEN-LAST:event_txt_unameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Login1;
    private javax.swing.JLabel btn_Login2;
    private javax.swing.JLabel btn_Login3;
    private javax.swing.JLabel btn_Login4;
    private javax.swing.JLabel btn_Login5;
    private javax.swing.JLabel btn_Login6;
    private javax.swing.JLabel btn_Login7;
    private javax.swing.JLabel btn_Login8;
    private javax.swing.JLabel btn_Login9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private javax.swing.JTextField password;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_uname;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
